# Generated by Django 2.2.7 on 2019-11-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
