# Generated by Django 2.2.7 on 2019-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=50)),
            ],
        ),
    ]
