# Generated by Django 2.2.7 on 2019-11-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
