# Generated by Django 2.2.7 on 2019-11-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('upassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usertags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=64, unique=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.userinfo')),
            ],
        ),
    ]
