# Generated by Django 2.2.7 on 2019-11-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_userinfo_usertags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usertags',
        ),
    ]
