# Generated by Django 2.2.7 on 2019-11-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_delete_usertags'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=64)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.userinfo')),
            ],
        ),
    ]
