# Generated by Django 2.2.7 on 2019-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_usertags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=32, unique=True)),
                ('pet_user', models.ManyToManyField(to='APP.userinfo')),
            ],
        ),
    ]
