# Generated by Django 2.2.7 on 2019-11-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_user',
            new_name='uname',
        ),
    ]
